[profile.default]
allow_internal_expect_revert = true
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
via-ir = false
optimizer-runs = 10_000_000

fs_permissions = [{ access = "read-write", path = "./"}]

solc ="0.8.24"

[fuzz]
runs = 500

[invariant]
runs = 256
depth = 500
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
